### ISSUE TITLE
Пустой экран

### ISSUE THREAD

**Issue by MonsWriter** [JivoSite/MobileSdk#19]
Здравствуйте!

Пытаемся подключить SDK в iOS приложении.

Я проследовал инструкциям в видео, но чат в приложении не отображается. Отображается индикатор загрузки по центру webView, как и положено, а после этого просто белый экран.
Подскажите, пожалуйста, в чем может быть причина?

Ниже две ссылки на видеофайлы, где я показываю свою инициализацию:

https://yadi.sk/i/p4YdQGrY3PrwYQ
https://yadi.sk/i/ptX7xxfM3PrxB4

**Comment by dimmetrius** [comment]
Добрый день. 

Проверьте следующие моменты:
1) папка html копируется в корень проекта
![Image1](https://jivo-dev.s3.amazonaws.com/mobile/sdk/GitHub/img/im1.png)
2) обратите внимание на опции при добавлении ресурса
![Image2](https://jivo-dev.s3.amazonaws.com/mobile/sdk/GitHub/img/im2.png)

3) в debug проверьте правильность подключенных ресурсов и строк
![Image3](https://jivo-dev.s3.amazonaws.com/mobile/sdk/GitHub/img/im3.png)

4) к webview можно подключиться на отладку в safari и посмотреть загрузку и логи

**Comment by MonsWriter** [comment]
Спасибо! Проблема решена.
