### ISSUE TITLE
Не грузит чат

### ISSUE THREAD

**Issue by Matsepura** [JivoSite/MobileSdk#2]
Сделал все как на видео. Но после открытия контроллера с `UIWebView` показывает `Loading` и потом белый экран. С чем может быть связано такое поведение?

**Comment by dimmetrius** [comment]
Добрый день. 

Проверьте следующие моменты:
1) папка html копируется в корень проекта
![Image1](https://jivo-dev.s3.amazonaws.com/mobile/sdk/GitHub/img/im1.png)
2) обратите внимание на опции при добавлении ресурса
![Image2](https://jivo-dev.s3.amazonaws.com/mobile/sdk/GitHub/img/im2.png)

3) в debug проверьте правильность подключенных ресурсов и строк
![Image3](https://jivo-dev.s3.amazonaws.com/mobile/sdk/GitHub/img/im3.png)

4) к webview можно подключиться на отладку в safari и посмотреть загрузку и логи

**Comment by Matsepura** [comment]
Спасибо! Папку html была скопирована не туда.
