### ISSUE TITLE
"plane_color":'red' - не работает

### ISSUE THREAD

**Issue by Matsepura** [JivoSite/MobileSdk#3]
Не могу изменить цвет самолетика (кнопка отправки), все остальные цвета поменялись.
Заранее спасибо за ответ!

**Comment by dimmetrius** [comment]
SDK обновлен, проблема с самолетиком исправлена. Можете обновить bundle.js в своем проекте

**Comment by Matsepura** [comment]
Благодарю за быстрый ответ.
Помогло.
