### ISSUE TITLE
Изменять текст приветсвия исходя от времени.

### ISSUE THREAD

**Issue by Matsepura** [JivoSite/MobileSdk#6]
А возможно ли изменять текст приветствия в разное время суток?
Например с 10 до 22 один текст, а в в отсальное время другой текст?
Как это возможно сделать?

Заранее, спасибо!

**Comment by Matsepura** [comment]
Может у Вас уже есть нужный `if` для `index_ru.html` ? =)

**Comment by dimmetrius** [comment]
``` javascript
var hour = new Date().getHours();
if(hour >= 10 && hour <= 22){
    jivo_config.active_message = "Здравствуйте! Я могу вам чем-то помочь с 10 до 22?",
}
``` javascript

**Comment by Matsepura** [comment]
Спасибо, сам сделал так:
надо изменить `index_ru/en.html` файлы следующим образом

` <script>
        var dateNow = new Date()
        var hours = dateNow.getHours()
        
        jivo_config = {
            // your config
        }
    
    if (hours > 9 && hours < 21) {
      jivo_config["active_message"] = "Open foo";
    } else {
      jivo_config["active_message"] = "Close foo";
    }
    
    </script>`
